### 채팅방 들어가기
GET http://localhost:8080/v1/chat/room/enter/f16bda54-6784-4ad2-a57b-91d95cf7b812
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjbGllbnRfaWQiOiIxIiwiY2xpZW50X2VtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlzcyI6ImNoYXQtYXBwIiwiaWF0IjoxNzAyMDA3MzA1LCJleHAiOjE3MDIwNDMzMDV9.01DQFvsDNeQ5A0gsqSMihouc9soJXQjbHgBq1P2va2dzZL6j8VsZgXGhfzz9u918v2_QwjZbYuitNmXHMB9DsA
Content-Type: application/json
