spring:
  application:
    name: my-spring
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:test}
    password: ${MYSQL_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    web:
      pageable:
        one-indexed-parameters: true
